"""Binary telemetry codec voor de CanSat <-> base station radio link.

Zie :mod:`cansat_hw.telemetry.codec` voor de eigenlijke pack/unpack-functies en
de format-spec van het 60-byte TLM-frame.
"""

from cansat_hw.telemetry.codec import (
	BINARY_FIRST_BYTE_MAX,
	FRAME_FORMAT,
	FRAME_SIZE,
	MODE_CONFIG,
	MODE_MISSION,
	MODE_NAMES,
	MODE_TEST,
	MODE_UNKNOWN,
	NUM_TAGS,
	RECORD_EVT,
	RECORD_HDR,
	RECORD_TLM,
	STATE_ASCENT,
	STATE_DEPLOYED,
	STATE_LANDED,
	STATE_NAMES,
	STATE_NONE,
	STATE_PAD_IDLE,
	STATE_UNKNOWN,
	TagDetection,
	TelemetryFrame,
	is_binary_packet,
	mode_for_string,
	mode_name,
	pack_cal,
	pack_mode_state,
	pack_tlm,
	state_for_mode_string,
	state_name,
	unpack_cal,
	unpack_mode_state,
	unpack_tlm,
)

__all__ = [
	"BINARY_FIRST_BYTE_MAX",
	"FRAME_FORMAT",
	"FRAME_SIZE",
	"MODE_CONFIG",
	"MODE_MISSION",
	"MODE_NAMES",
	"MODE_TEST",
	"MODE_UNKNOWN",
	"NUM_TAGS",
	"RECORD_EVT",
	"RECORD_HDR",
	"RECORD_TLM",
	"STATE_ASCENT",
	"STATE_DEPLOYED",
	"STATE_LANDED",
	"STATE_NAMES",
	"STATE_NONE",
	"STATE_PAD_IDLE",
	"STATE_UNKNOWN",
	"TagDetection",
	"TelemetryFrame",
	"is_binary_packet",
	"mode_for_string",
	"mode_name",
	"pack_cal",
	"pack_mode_state",
	"pack_tlm",
	"state_for_mode_string",
	"state_name",
	"unpack_cal",
	"unpack_mode_state",
	"unpack_tlm",
]
